spring.application.name=covid_19
# 使用絕對路徑或相對於專案根目錄的路徑
spring.datasource.url=jdbc:sqlite:src/main/resources/covid19.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA 設定
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true